sonar.organization=ph1l96
sonar.projectKey=ph1l96_cicd_test
sonar.projectName=CICD-Pipeline-Agency
sonar.sources=composeApp/src/commonMain,composeApp/src/androidMain,composeApp/src/wasmJsMain
sonar.tests=composeApp/src/commonTest
sonar.language=kotlin
sonar.sourceEncoding=UTF-8
